version: '3'

services:
  app:
    build:
      context: ./backend/phpserver
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend/phpserver:/var/www
    ports:
      - 8000:8000
      - 8080:8080
      - 9000:9000

    depends_on:
        - mysql
        - redis



  mysql:
    build:
        context: ./backend/mysql
        dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./backend/dbdata:/var/lib/mysql
    ports:
      - 3301:3301

    

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 80:80